version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/Transactions-0.1-SNAPSHOT.jar
    - appspec.yml
  discard-paths: yes
  secondary-artifacts:
    artifact1:
      files:
        - Scripts/runApp.sh
      discard-paths: no