server:
  port: 8080

spring:
  jpa:
    generate-ddl: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/smartinvest?useTimezone=true&serverTimezone=UTC
    username: root
    password: root

cloud:
  aws:
    region:
      #for SSM parameter store
      static: sa-east-1
    stack:
      #for localhost testing
      auto: false

