spring:
  application:
    name: Transactions

  profiles:
    active: @activatedProperties@
#    active: prod

#SpringBootAdmin server address
  boot:
    admin:
      client:
        url: http://${SPRING_ADMIN_URL:localhost}:${SPRING_ADMIN_PORT:8081}

#expose actuator endpoints
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: @project.name@
    version: @project.version@


