spring:
  profiles:
    active: @activatedProperties@
#    active: prod

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
info:
  app:
    name: @project.name@
    version: @project.version@
